version: "3.8"

services:
    mysql:
        container_name: capstone_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: root
            MYSQL_PASS: admin
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - 3306:3306

    mongo:
        container_name: capstone_mongo
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - mongo-volume:/data/db
        ports:
            - 27017:27017

    mongo-express:
        container_name: capstone_mongo_express
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin

    # kafka: 
    #     container_name: capstone_kafka
    #     image: bitnami/kafka:latest
    #     ports:
    #         - '9092:9092'
    #     environment: 
    #         - KAFKA_BROKER_ID=1
    #         - KAFKA_LISTENER=PLAINTEXT://:9092
    #         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    #         - KAFKA_ZOOKEEPER_CONNECT=capstone_zookeeper:2181
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #     depends_on: 
    #         - zookeeper

    # zookeeper:
    #     container_name: capstone_zookeeper
    #     image: bitnami/zookeeper:latest
    #     ports: 
    #         - '2181:2181'
    #     environment:
    #         - ALLOW_ANONYMOUS_LOGIN=yes


volumes:
    mysql-volume:
    mongo-volume:
