version: "3.8"

services:
    mysql:
        container_name: capstone_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_PASS: admin
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./server/database/backup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
            - 3306:3306

    kafka:
        container_name: capstone_kafka
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9094"
        environment:
            HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
            KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        depends_on:
            - zookeeper
        healthcheck:
            test:
                [
                    "CMD",
                    "kafka-topics.sh",
                    "--list",
                    "--zookeeper",
                    "zookeeper:2181",
                ]
            interval: 30s
            timeout: 10s
            retries: 4
    kafka-setup:
        image: phuchung276/capstone_kafka_setup:latest
        container_name: capstone_kafka_setup
        build:
            context: ./server/kafka-setup
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_BOOTSTRAP_SERVER=broker:29092
        depends_on:
            kafka:
                condition: service_healthy

    zookeeper:
        container_name: capstone_zookeeper
        image: bitnami/zookeeper:latest
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    redis:
        container_name: capstone_redis
        image: bitnami/redis:latest
        volumes:
            - redis-volume:/bitnami/redis/data
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL
volumes:
    mysql-volume:
    redis-volume:

networks:
    default:
        name: capstone
