version: "3.8"

services:
    frontend:
        container_name: capstone_frontend
        image: phuchung276/capstone_frontend:latest
        build:
            context: ./server/frontend
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        volumes:
            - "/frontend/node_modules"
        depends_on:
            backend:
                condition: service_healthy

    backend:
        container_name: capstone_backend
        image: phuchung276/capstone_backend:latest
        ports:
            - 8080:8080
        depends_on:
            kafka:
                condition: service_healthy
            mysql:
                condition: service_healthy
        healthcheck:
            test: "curl --fail --silent localhost:8090/actuator/health | grep UP || exit 1"
            interval: 20s
            timeout: 5s
            retries: 5
            start_period: 40s

    faiss:
        container_name: capstone_faiss
        image: phuchung276/capstone_faiss:latest
        build:
            context: ./server/faiss
        depends_on:
            kafka:
                condition: service_healthy

networks:
    default:
        name: capstone
