version: "3.8"

services:
    faiss:
        container_name: capstone_faiss
        image: phuchung276/capstone_faiss:latest
        build:
            context: ./server/faiss
        depends_on:
            - kafka

    mysql:
        container_name: capstone_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_PASS: admin
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./server/database/backup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
            - 3306:3306

    kafka:
        container_name: capstone_kafka
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENER=PLAINTEXT://kafka:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafka-setup:
        image: phuchung276/capstone_kafka_setup:latest
        container_name: capstone_kafka_setup
        build:
            context: ./server/kafka-setup
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_BOOTSTRAP_SERVER=broker:29092
        depends_on:
            - kafka
            - zookeeper

    zookeeper:
        container_name: capstone_zookeeper
        image: bitnami/zookeeper:latest
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    redis:
        container_name: capstone_redis
        image: bitnami/redis:latest
        volumes:
            - redis-volume:/bitnami/redis/data
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL
volumes:
    mysql-volume:
    redis-volume:

networks:
    default:
        name: capstone
