version: "3.8"

services:
    mysql:
        container_name: capstone_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: root
            MYSQL_PASS: admin
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - 3306:3306

    kafka:
        container_name: capstone_kafka
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        volumes:
            - kafka-volume:/bitnami/kafka
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENER=PLAINTEXT://kafka:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://34.87.104.34:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper

    zookeeper:
        container_name: capstone_zookeeper
        image: bitnami/zookeeper:latest
        volumes:
            - zookeeper-volume:/bitnami/zookeeper
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    face-server:
        container_name: capstone_face_server
        build: ./face-server
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./face-server:/face-server
            - ./utils:/utils
            - ./ailibs:/ailibs
            - ./ailibs_data:/ailibs_data
    # faiss-server:
    #     container_name: capstone_faiss
    #     build: ./faiss_server
    #     expose:
    #         - 6000
    #     ports:
    #         - 6000:6000
    #     volumes:
    #         - ./faiss_server:/faiss-server

volumes:
    mysql-volume:
    kafka-volume:
    zookeeper-volume:
    nginx-volume:
